env:
  IMAGE_NAME: development-playground
  REGISTRY_HOSTNAME: multiversx

name: Build & push Docker image (Release)

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Simulate release version (e.g., v0.4.2)'
        required: false
        default: ''
        type: string

jobs:
  build:
    strategy:
      matrix:
        arch:
          - { runner: ubuntu-latest, platform: linux/amd64, platform_tag: linux_amd64 }
          - { runner: ubuntu-24.04-arm, platform: linux/arm64, platform_tag: linux_arm64 }
    runs-on: ${{ matrix.arch.runner }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            ${{ (github.event_name == 'release' && format('type=ref,event=tag')) || (github.event.inputs.version != '' && format('type=raw,value={0}', github.event.inputs.version)) || '' }}

      - name: Build and push per-arch image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./.devcontainer
          file: ./.devcontainer/Dockerfile
          push: true
          tags: ''
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,push-by-digest=true,name-canonical=true

      - name: Export image digest
        if: steps.build.outputs.digest != ''
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          echo "${digest#sha256:}" > ${{ runner.temp }}/digests/${{ matrix.arch.platform_tag }}

      - name: Upload image digest
        if: steps.build.outputs.digest != ''
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.arch.platform_tag }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: ignore
          retention-days: 1

  manifest:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            ${{ (github.event_name == 'release' && format('type=ref,event=tag')) || (github.event.inputs.version != '' && format('type=raw,value={0}', github.event.inputs.version)) || '' }}

      - name: Download image digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Create and push manifests
        working-directory: ${{ runner.temp }}/digests
        run: |
          amd64_digest=$(cat linux_amd64)
          arm64_digest=$(cat linux_arm64)
          
          amd64_ref="${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NAME }}@sha256:${amd64_digest}"
          arm64_ref="${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NAME }}@sha256:${arm64_digest}"
          
          echo '${{ steps.meta.outputs.json }}' | jq -cr '.tags[]' | while read -r tag; do
            docker buildx imagetools create -t "$tag" "$amd64_ref" "$arm64_ref"
          done
