env:
  IMAGE_NAME: development-playground
  REGISTRY_HOSTNAME: multiversx

name: Build & push Docker image (Release)

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Simulate release version (e.g., v0.4.2)'
        required: false
        default: ''
        type: string

jobs:
  build:
    strategy:
      matrix:
        arch:
          - { runner: ubuntu-latest, platform: linux/amd64 }
          - { runner: ubuntu-24.04-arm, platform: linux/arm64 }
    runs-on: ${{ matrix.arch.runner }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            ${{ github.event.inputs.version != '' && format('type=raw,value={0}', github.event.inputs.version) || '' }}

      - name: Build and push per-arch image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./.devcontainer
          file: ./.devcontainer/Dockerfile
          push: true
          tags: ${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NAME }}:temp-${{ matrix.arch.platform }}-${{ github.run_id }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,push-by-digest=true,name-canonical=true

      - name: Export image reference
        if: steps.build.outputs.digest != ''
        run: |
          mkdir -p ${{ runner.temp }}/images
          image_ref="${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NAME }}:temp-${{ matrix.arch.platform }}-${{ github.run_id }}@${{ steps.build.outputs.digest }}"
          echo "$image_ref" > ${{ runner.temp }}/images/ref.txt

      - name: Upload image reference
        if: steps.build.outputs.digest != ''
        uses: actions/upload-artifact@v4
        with:
          name: images-${{ matrix.arch.platform }}
          path: ${{ runner.temp }}/images/ref.txt
          if-no-files-found: ignore
          retention-days: 1

  manifest:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_HOSTNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            ${{ github.event.inputs.version != '' && format('type=raw,value={0}', github.event.inputs.version) || '' }}

      - name: Download image references
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/images
          pattern: images-*
          merge-multiple: true

      - name: Create and push manifests
        run: |
          amd64_ref=$(cat ${{ runner.temp }}/images/images-linux-amd64/ref.txt)
          arm64_ref=$(cat ${{ runner.temp }}/images/images-linux-arm64/ref.txt)
          
          echo '${{ steps.meta.outputs.json }}' | jq -cr '.tags[]' | while read -r tag; do
            docker buildx imagetools create -t "$tag" "$amd64_ref" "$arm64_ref"
          done
